### ISSUE TITLE
The access token provided doesn't work

### ISSUE THREAD

**Issue by jorgegaticav** [maslick/keycloak-android-native#3]
Hi maslick,
I'm testing the app with my own keycloak server. When I do the login in the browser and return to the app, It shows all the data (access token, refresh token, etc.) . However when I tried to use the provided access token in a request using Postman it is invalid. 
Any suggestions? thank you!

**Comment by maslick** [comment]
Hi @jorgegaticav !

Can you provide some more info (REST endpoint, HTTP status code, etc.)? And what Keycloak client type are you using? In a basic scenario you would have two Keycloak clients:

- public (obtain token on the front-end)
- bearer-only (secure your REST API with this client)

I also recommend you to parse the token and analyze it using ``jwt.io``.

**Comment by maslick** [comment]
P.S. For debugging I have created a CLI tool called [brauzie](https://github.com/maslick/brauzie) that can help you fetch and analyse your JWT tokens (scopes, roles, etc.). It could be used for both public and confidential clients.
