### ISSUE TITLE
How do I use it?

### ISSUE THREAD

**Issue by dalu** [maslick/keycloak-android-native#4]
Pretty new to Android development.
I know there are 2 main build and dependency tools, maven and gradle.

How do add your lib to the dependencies?
And can I even use it when I created my project with Java and not Kotlin?

**Comment by maslick** [comment]
Hi @dalu !
It's not a library, but rather a showcase. You can clone the repo and edit it according to your needs.
Unfortunately, it cannot be rewritten to Java. It's using Koin, a Kotlin-specific dependency injection framework. I would recommend you to invest some effort into Kotlin, it's really worth that :)

**Comment by dalu** [comment]
Thanks but I don't have the time to learn yet another language :)
I'm satisfied with Go on the server side and really only need the oidc/oauth2 issue solved and grpc to work.
Well thanks for the answer, moving along then.
